/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteImport } from './routes/project.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/milestones': typeof MilestonesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risks': typeof RisksRoute
  '/settings': typeof SettingsRoute
  '/project/$id': typeof ProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/milestones': typeof MilestonesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risks': typeof RisksRoute
  '/settings': typeof SettingsRoute
  '/project/$id': typeof ProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/milestones': typeof MilestonesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risks': typeof RisksRoute
  '/settings': typeof SettingsRoute
  '/project/$id': typeof ProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/milestones'
    | '/reset-password'
    | '/risks'
    | '/settings'
    | '/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/milestones'
    | '/reset-password'
    | '/risks'
    | '/settings'
    | '/project/$id'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/milestones'
    | '/reset-password'
    | '/risks'
    | '/settings'
    | '/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MilestonesRoute: typeof MilestonesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RisksRoute: typeof RisksRoute
  SettingsRoute: typeof SettingsRoute
  ProjectIdRoute: typeof ProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MilestonesRoute: MilestonesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RisksRoute: RisksRoute,
  SettingsRoute: SettingsRoute,
  ProjectIdRoute: ProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
